const CIDADES = {
    "Brunópolis": "bnu",
    "Campos Novos": "cnv",
    "Curitibanos": "ctb",
    "Fraiburgo": "fbg",
    "Frei Rogério": "frr",
    "Iomerê": "iom",
    "Monte Carlo": "mca",
    "Pinheiro Preto": "ppr",
    "Videira": "vda",
    "Agronômica": "agr",
    "Aurora": "aur",
    "Ituporanga": "itu",
    "Lontras": "lon",
    "Petrolândia": "ptl",
    "Pouso Redondo": "prd",
    "Rio do Sul": "rsl",
    "Campo Belo do Sul": "cbs",
    "Capão Alto": "cat",
    "Correia Pinto": "cpo",
    "Lages": "lgs",
    "Ponte Alta": "pta",
    "Apiúna": "api",
    "Ascurra": "asc",
    "Blumenau": "blu",
    "Indaial": "idl",
    "Rodeio": "rod",
    "Água Doce": "ace",
    "Catanduvas": "ctv",
    "Herval d'Oeste": "hdo",
    "Ibicaré": "ibc",
    "Ipira": "ipi",
    "Joaçaba": "jba",
    "Luzerna": "lzn",
    "Piratuba": "ptb",
    "Salto Veloso": "svs",
    "Tangará": "tan",
    "Treze Tílias": "tzs",
    "Anita Garibaldi": "ant",
    "Caçador": "cdr",
    "Macieira": "mra",
    "Ponte Alta do Norte": "pan",
    "São Cristóvão do Sul": "sct",
    "Araquari": "arq",
    "Balneário Barra do Sul": "bbs",
    "Brusque": "brq",
    "Camboriú": "cmb",
    "Campo Alegre": "cal",
    "Guaramirim": "grm",
    "Jaraguá do Sul": "jas",
    "Joinville": "jve",
    "Luiz Alves": "mas",
    "Massaranduba": "mas",
    "São Francisco do Sul": "sfs",
    "Schroeder": "sch",
    "Erval Velho": "evv",
    "Lacerdópolis": "ldp",
    "Rio dos Cedros": "rdc",
    "Balneário Piçarras": "bpi",
    "Barra Velha": "bve",
    "Navegantes": "nav",
    "Penha": "pen",
    "São João do Itaperiú": "sji",
    "Garuva": "gva",
    "Itapoá": "itp"
};

document.addEventListener('DOMContentLoaded', () => {
    const selectCidade = document.getElementById('cidade');

    for (const [nomeCidade, sigla] of Object.entries(CIDADES)) {
        const option = document.createElement('option');
        option.value = sigla;
        option.textContent = nomeCidade;
        selectCidade.appendChild(option);
    }
});
